# Generated by Django 5.1 on 2024-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('book_cover', models.CharField(max_length=255)),
                ('pdf_cover', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
    ]
