# Generated by Django 5.1 on 2024-08-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='pdf_cover',
            new_name='pdf_file',
        ),
    ]
