# Generated by Django 5.1 on 2024-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_rename_pdf_cover_buku_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='book_cover',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='buku',
            name='desc',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='buku',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
