# Generated by Django 5.1 on 2024-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_alter_buku_book_cover_alter_buku_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='desc',
            field=models.TextField(),
        ),
    ]
