# Generated by Django 5.1 on 2024-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_alter_buku_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='desc',
            field=models.CharField(max_length=10000),
        ),
    ]
