# Generated by Django 5.1 on 2024-08-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_alter_buku_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
